name: cont-deploy-dev
on:
    push:
        branches: [ master ]
jobs:
    prep_and_deploy_to_s3:
        runs-on: ubuntu-latest
        strategy:
          matrix:
            node-version: [14.x]
        steps:
            - name: Configure AWS Credentials
              uses: aws-actions/configure-aws-credentials@v1
              with:
                aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                aws-region: ${{ secrets.AWS_REGION }}
            - name: Check out repository
              uses: actions/checkout@v2
            - name: Install Packages
              run: npm i
            - name: Run unit tests
              run: CI=true npm test
            - name: Build static site
              run: npm run build
            - name: Deploy static site to S3 bucket
              run: aws s3 sync ./build s3://mtg-price-ui-dev --delete